### ISSUE TITLE
Short Rest Limit

### ISSUE THREAD

**Issue by LogosWorks** [ZerdBG3/DnD-Rebalancing#10]
I did a thing!
[https://www.nexusmods.com/baldursgate3/mods/15](https://www.nexusmods.com/baldursgate3/mods/15)
For that I just set to 4 rests

What is the right amount of rests. 5e has a limit... 24 as there are 24 hours in the day.

That said currently the game heals party on every rest.

We may want to implement hit dice if we want large amount of short rests.

TO up the limit just change

line 451 of Public/Shared/Stats/Generated/Data/Data.txt
`key "MaxShortRestPoints","1"`

**Comment by FelipeRenault** [comment]
Thanks for the report. I might include this in my mod and credit you for the finding!
