### ISSUE TITLE
Remove Backstabbing

### ISSUE THREAD

**Issue by FelipeRenault** [ZerdBG3/DnD-Rebalancing#13]

**Comment by FelipeRenault** [comment]
Apparently, Larian didn't even tried to make this a light weapon feature, they just decided to make it available on a per-character basis, which makes me wonder why the tutorial says it's only for light weapons
The `Character.txt` file had the entry `_Hero` with `Backstab` as a passive, simply removing that removes backstab from every character that inherits that.
There were no specific character entry that gives backstab, neither in `Shared` nor in `Gustav`, which means, apparently, it was a bonus just for players

**Comment by DubhHerder** [comment]
Hi, Thanks for the great mod. 

I just wanted to let you know that this issue might need to be reopened at some point, depending on whether you only wanted to remove backstab from the players options and allow the NPCs to continue using it or if you wanted to removed it completely from the game. 

As of patch 4, Larian is using a different way to implement backstab and the attribute is not limited to the `_Hero` entry (and the blocks built on `_Hero`). 

There are currently individual `Backstab` entries in both `Shared` (30 entries) and `Gustav`  (12 entries) that cover most of the base NPC entries for races and some particular individual types. 

I'm not sure if it's something that is worth changing while the game is still in EA or not but i just wanted to let you know if you didn't already.

**Comment by FelipeRenault** [comment]
I'm against having different ruling for npcs and players (except for those clearly stated on the Monster's Manual, such as rechargeable actions). Thus, I'll remove backstab for those additional entries.

I'd want to avoid having to edit entries from `Gustav`, but I think it won't be avoidable. Thanks for reporting it.

**Comment by FelipeRenault** [comment]
Luckly, there was an easier solution, which was to simply remove the boost the Passive gives (#72). This is easier, more reliable and more compatible with other mods.
