### ISSUE TITLE
Correct enemies AC as an alternative mod

### ISSUE THREAD

**Issue by JHorbach** [ZerdBG3/DnD-Rebalancing#15]
Implementing this will up the game difficulty a lot, but enemies that are using armors should have their AC respecting that, like a leather amor has AC 11 +Dex Bonus.
When no armor it should be natural armor +Dex.

My suggestion is to implement this but as an alternative because it will make the game pretty hard.

**Comment by FelipeRenault** [comment]
Hmm... I'd rather not fiddle much into enemies statistics. They changed some of the monsters in the game, giving them different abilities, stats, etc. If I were to make them completely faithful to the Monster's Guide, there would be several implications to the pace of the game, not to mention the never ending job to alter tons of monsters
