### ISSUE TITLE
Fix Weapon Properties

### ISSUE THREAD

**Issue by AshnakAGQ** [ZerdBG3/DnD-Rebalancing#19]
Right now a lot of the important properties of weapons are either inert or downright missing.

Small creatures should be able to wield "Heavy" weapons without disadvantage. This includes Halflings but also Goblins.

Crossbows shouldn't be able to fire more than once a turn because of the "Loading" Property (without a crossbow expert feat), though with Action Surge, Horde Breaker, or potion of speed, I'm pretty sure you can in this game.

You should be able to throw a "Throw" and equipped weapon instead of attacking with it, using the same modifier as the attack would normally have. So normally strength unless the weapon has Finesse.

**Comment by FelipeRenault** [comment]
For a lot of those things, I think it's just that Larian didn't implement yet, but they will. That goes for Heavy weapons not being equippable by small races, and the throw weapon (which is something they really enjoy, so they'll implement it soon)
For the "Loading" property, that's not how the rules work. The "Loading" property states:

> Loading. Because of the time required to load this weapon, you can fire only one piece of ammunition from it when you use an action, bonus action, or reaction to fire it, regardless of the number of attacks you can normally make.

This means that if you get multiple Action in one turn by any means, each Action can fire one shot. That's the case with Action Surge and Potion of Speed. This rule is most impacting when considering something like lvl 5 Extra Attack (multiple classes):

> Extra Attack allows you to make one additional attack when you take the Attack action. (You may also move between the two attacks). Fighters gain the ability to gain two or three additional attacks at higher levels, so a 20th level fighter is able to make 4 attacks when they take the Attack action.

**Comment by AshnakAGQ** [comment]
True, they will probably implement these eventually. Otherwise they would have bothered to put in the properties. 
Didn't know that about the loading property. It still shouldn't work with Horde Breaker in that case.

**Comment by FelipeRenault** [comment]
That is true, Horde Breaker should't work with crossbows. But that seems a little too much trouble to fix it, and I hope they'll fix it
