### ISSUE TITLE
Torch is too good.

### ISSUE THREAD

**Issue by AshnakAGQ** [ZerdBG3/DnD-Rebalancing#21]
The torch does 1d4 damage + 1d4 fire base damage (2d4 with no resistance). It is a simple weapon so can be wielded by pretty much everyone. It stays lit forever so no need to reapply dip. It is light so it can be dual-wielded. It also acts as a light source. It's just better than any other one-handed weapon on a strength build unless you go out of your way to light your weapons every combat.

It should only do 1d4 bludgeoning (improvised weapon) or 1 fire damage when lit (maybe as the special weapon attack). At most, it should only do 1d4 + 1 fire damage.

**Comment by FelipeRenault** [comment]
I'll probably reduce dip damage from 1d4 to +1 static damage. That goes for poison coating as well.
But I really like the idea of making a torch have a special attack. Maybe I'll let it have 1d4 bludgeoning even when lit, and give it a special attack that deals only 1d4 fire. What do you think?

**Comment by AshnakAGQ** [comment]
Sounds good. Not about removing the dip damage entirely though. You can use a fire-dipped item to ignite surfaces by either swinging over it or dipping into them. Not sure if that relies on fire damage or not. 

I think since the torch is an improvised weapon imitating the club, it should a similar ability. "Smash" normally just doubles the strength modifier. You could just add an extra d4 fire damage, or just give it the smash ability.

**Comment by FelipeRenault** [comment]
Per #9, weapon abilities are removed. I'd create an exception for torches to give them a new one that would deal fire damage only

**Comment by LogosWorks** [comment]
I would say dip converts bludgeoning to fire damage. It also lights the torch and lets off light. Fire damage overcomes resistance to bludgeoning.

**Comment by FelipeRenault** [comment]
Just a feedback: I figured out why the torch kept dealing 1d4 damage even after I altered the `DIPPED_FIRE` damage and I managed to actually change that too so torches can now deal 1 static fire damage bonus like other weapons.
I tried adding a new spell to a burning torch that deals 1d4 fire damage (without modifiers), but I didn't manage to make that weapon spell only available when the torch is burning, so I'll settle just for the static 1 fire damage increase
