### ISSUE TITLE
Change High Ground

### ISSUE THREAD

**Issue by FelipeRenault** [ZerdBG3/DnD-Rebalancing#26]
High Ground should provide half cover against enemies attacking from below (+2 AC) and the usual range extension (which is already given by default).
The Advantage on attack rolls should be removed, together with the Disadvantage from Low Ground

**Comment by LogosWorks** [comment]
This seems a good early solution, but I think we can find a better way to implement cover. High-low ground leaves so many important factors out?

**Comment by FelipeRenault** [comment]
I highly doubt we can implement better cover solutions without Larian wanting to do it themselves. Cover checks require a processing on the positions of each character and LoS checks, which is very hard to do outside the low level layer of the game

**Comment by FelipeRenault** [comment]
Release [v0.3.4.3](https://github.com/ZerdBG3/DnD-Rebalancing/releases/tag/v0.3.4.3) to temporarily remove high ground advantage
