### ISSUE TITLE
Jump/Fly as non-action

### ISSUE THREAD

**Issue by LogosWorks** [ZerdBG3/DnD-Rebalancing#3]
RAW Jump is not an action but rather a type of movement.

**Possible Implementation:**
Click the button to activate activate that type of movement. Then next move command is done as a jump/fly.
Possibly make this a toggle on/off.

### Jumping
PHB p182
Your Strength determines how far you can jump.
####Long Jump
PHB p182
When you make a long jump, you cover a number of feet up to your Strength score if you move at least 10 feet on foot immediately before the jump. When you make a standing long jump, you can leap only half that distance. Either way, each foot you clear on the jump costs a foot of movement.
This rule assumes that the height of your jump doesn't matter, such as a jump across a stream or chasm. At your DM's option, you must succeed on a DC 10 Strength (Athletics) check to clear a low obstacle (no taller than a quarter of the jump's distance), such as a hedge or low wall. Otherwise, you hit it.
When you land in difficult terrain, you must succeed on a DC 10 Dexterity (Acrobatics) check to land on your feet. Otherwise, you land prone.
####High Jump
PHB p182
When you make a high jump, you leap into the air a number of feet equal to 3 + your Strength modifier (minimum of 0 feet) if you move at least 10 feet on foot immediately before the jump. When you make a standing high jump, you can jump only half that distance. Either way, each foot you clear on the jump costs a foot of movement. In some circumstances, your DM might allow you to make a Strength (Athletics) check to jump higher than you normally can.
You can extend your arms half your height above yourself during the jump. Thus, you can reach above you a distance equal to the height of the jump plus 1½ times your height.

**Comment by FelipeRenault** [comment]
The bigger problem is this: "if you move at least 10 feet on foot immediately before the jump"
The standing long jump is already implemented, we can easily make it cost no action and only cost movement, but I think we should remove this option in-combat. It's being used as a disengage to avoid AoO, which definitely isn't the intended usage (by PHB's rules)

I don't think the High Jump is worth implementing, as the normal Jump already does this job

**Comment by LogosWorks** [comment]
Agreed. Disengage is needed to prevent AoO.
I think retooling the standing long jump would be more core like. You can long jump in combat but if you don't also disengage, you will get an AoO. Not sure how hard it would be to pull the disengage off the jump action though.
Some testing is needed to determine if the current jump uses Strength score, or half strength score.
Agreed on pass for High Jump.
And remove disengage from Fly.

TODO:

- Fly: Remove Disengage, Remove Action
- Jump: Remove Disengage, Remove Action
- Test Jump distance and possibly cut it in half while in combat. to remove running long jump.

**Comment by LogosWorks** [comment]
Testing shows: 14 strength jumps 24 feet...
Yikes... well lets just say the distances are good where they are. with the amount of jumping the game requires changing that may break things.

**Comment by FelipeRenault** [comment]
The hardest thing will be to force an AoO on a jumping target... I can't make it an Out of Combat feature because a lot of times you need to jump to get to higher places, but I can't see a way to force an AoO.
Maybe I can make it so Jump isn't usable if you're threatened, thus you'll be forced to get out of enemies range (and take an AoO or Disengage) before jumping

**Comment by LogosWorks** [comment]
Correct. If you were to have 30 strength, or 10 strength with the jump spell the human would jump 30 feet or their full movement. note the rule...

`...Either way, each foot you clear on the jump costs a foot of movement...`
I like the idea with If threatened, no jump. seems simple enough.

**Comment by FelipeRenault** [comment]
Now Jump is no longer an Action, but can't be used while Threatened. Closed by #32
