### ISSUE TITLE
Fast Hands?

### ISSUE THREAD

**Issue by Merlex-Necromancer** [ZerdBG3/DnD-Rebalancing#31]
I'm using your Rebalancing mod. When I leveled to 3rd, I had Astarion take the Thief subclass; but the button for Fast Hands never appeared. It's not on my character sheet, nor in my inventory, nor anywhere else.

**Comment by FelipeRenault** [comment]
BG3 made Thiefs get an extra Bonus Action instead
Fast Hands is not yet implementend on the mod as it's not listed on the [Features](https://github.com/ZerdBG3/DnD-Rebalancing/blob/main/Features.md) section
