### ISSUE TITLE
Upcasting Spells

### ISSUE THREAD

**Issue by Arkenny** [ZerdBG3/DnD-Rebalancing#37]
To make the Upcasting of any spell feel less clunky adding a popup window that will work in the same way as Arcane Recovery window from Wizard will improve quality of life, instead of 2 versions of the same spell clogging up your Hotbar.

**Comment by FelipeRenault** [comment]
I truly think this is a must, but doing it will require immense work, so don't expect me to do it anytime soon
Not only that, but I don't know how this would interact with spells that already open a panel (like Hex)

**Comment by gnufred** [comment]
Looks to me like this request is out of scope for this mod. I definitely agree the spell casting UI is horrible, but that has nothing to do with making BG3 content follow books RAW.

**Comment by FelipeRenault** [comment]
Regardless, that's something that had just been done by Larian's latest patch
Unfortunately, that's the same patch that made packed mods stop working :roll_eyes:
