### ISSUE TITLE
Dodge Action Implementation

### ISSUE THREAD

**Issue by LogosWorks** [ZerdBG3/DnD-Rebalancing#4]
### Dodge
PHB p192
 
When you take the Dodge action, you focus entirely on avoiding attacks. Until the start of your next turn, any attack roll made against you has disadvantage if you can see the attacker, and you make Dexterity saving throws with advantage. You lose this benefit if you are incapacitated (as explained in the appendix) or if your speed drops to 0.

**Comment by LogosWorks** [comment]
When monks are added their code for patient defense could be used to make this work... If it must wait that long.

**Comment by FelipeRenault** [comment]
I really want this Action, but I do believe they'll implement it soon. I'll take a look into implementing it, but only if it's easy to do, otherwise I'll rather wait

**Comment by LogosWorks** [comment]
100% agreement! I just wanted to get it on the issue board.

**Comment by FelipeRenault** [comment]
I implemented it, but I didn't waste a lot of time on the removal part when you're incapacitated or immobilized. For now, it's just a tad stronger than intended, but the rest works fine
