### ISSUE TITLE
Two Weapon Fighting

### ISSUE THREAD

**Issue by Dapoulp** [ZerdBG3/DnD-Rebalancing#40]
There are some issues when using 2 weapons:

1. Even without the Two Weapon Fighting style, ability modifer is added to off-hand damage.
2. Abitility modifier is not added to off-hand hit chance
3. Dual Wielder feat doesn't grant +1 AC when dualwielding

For the second point, one way is to substract the ability modifier to off hand damage until you get the fighting style. The only counterpart is the combat log where you'll see "+ X - X + X"

For the third point, it can be fixed like that:
File: Passive.txt

> new entry "DualWielder_BonusAC"
type "PassiveData"
data "DisplayName" "Passive_DualWielder_BonusAC_DisplayName"
data "Description" "Passive_DualWielder_BonusAC_Description"
**data "Boosts" "IF(FightingStyle_TwoWeapons(context.Source)):AC(1)"**

**Comment by FelipeRenault** [comment]
I can kinda hack the modifier being on off-hand attack rolls, but it will use the same ability modifier of the main hand weapon (which is almost always fine - it's very rare for someone to use a finesse and non-finesse weapon at the same time). I'll try to include the negative modifier damage and see how it goes

Thanks for the suggestion for topic 3. If you want to open a pull request for that, feel free to do so. If you don't want, I'll test it out soon(ish)

**Comment by FelipeRenault** [comment]
The fix assumes the player is using either two finesse or two non-finesse weapons
Attack rolls is based of the Main Weapon, so it rolls with the ability modifier. It might also use some bonuses from magic weapons, unfortunately
Damage rolls subtracts the Dexterity Modifier if it's a finesse weapon or Strenght Modifier if it's not. The `WieldingFinesseWeapon` check isn't super precise either, it returns true if the character is holding a finesse weapon in either hand
```
data "SpellRoll" "Attack(AttackType.MeleeWeaponAttack)"
data "SpellSuccess" "IF(WieldingFinesseWeapon(context.Source)):DealDamage(max(1,OffhandMeleeWeapon)-max(0,DexterityModifier), OffhandMeleeWeaponDamageType);IF(not WieldingFinesseWeapon(context.Source)):DealDamage(max(1,OffhandMeleeWeapon)-max(0,StrengthModifier), OffhandMeleeWeaponDamageType);ExecuteWeaponFunctors(OffHand)"
```
The end result, given the character is using two weapons of the same type, is exactly what we expect. The appropriate modifier is added to the attack roll, and the modifier is canceled on the damage roll (unless it's negative)
