### ISSUE TITLE
Two-Weapon Fighting Action require Attack Action

### ISSUE THREAD

**Issue by LogosWorks** [ZerdBG3/DnD-Rebalancing#6]
You are not able to use Two-Weapon Fighting unless you have ALREADY taken the attack action.
### Two-Weapon Fighting
PHB p195

When you take the Attack action and attack with a light melee weapon that you're holding in one hand, you can use a bonus action to attack with a different light melee weapon that you're holding in the other hand. You don't add your ability modifier to the damage of the bonus attack, unless that modifier is negative.If either weapon has the thrown property, you can throw the weapon, instead of making a melee attack with it.

**Comment by FelipeRenault** [comment]
Did it without Larian's help \o/
