### ISSUE TITLE
Two-Weapon Fighting Remove reference to mainhand & offhand

### ISSUE THREAD

**Issue by LogosWorks** [ZerdBG3/DnD-Rebalancing#8]
RAW Rules do not define a main hand and an off hand. The attack action is made with weapons you hold and Two Weapon Fighting is done with "...a different light melee weapon that you're holding in the other hand."
This is important when the wielded weapons are different and after extra attack is gained.
If L and R are hands, A is Attack Action and B is Two-Weapon Fighting Bonus Action; Attack patterns can look as follows.
Without Extra Attack
A(R) B(L)
A(L) A(R)
With Extra Attack
A(RR) B(L)
A(LL) A(R)
A(R & L) B(R or L)

**Comment by FelipeRenault** [comment]
Unfortunately, Larian made the distinction between main hand and offhand on their engine since DOS1. I think that's something they brought from their engine and left unchecked and it's definitely hardcoded :confused:
