### ISSUE TITLE
[Armor] Heavy Armors

### ISSUE THREAD

**Issue by FelipeRenault** [ZerdBG3/DnD-Rebalancing#82]
Larian didn't even include Splint and Plate armors on EA. Your best Heavy Armor option is a Chain Mail, which might not even be found depending on how you play the game. So I decided to add heavy armors to some traders and loot spots to give more options to Str-based characters (and allow them to properly dump Dexterity, if they so wish)

Comment below where I should place the heavy armors

**Comment by FelipeRenault** [comment]
- The Tiefling Blacksmith from the Druid's Grove will have a Chain Mail

**Comment by DubhHerder** [comment]
Possibly Novice Grat  under the `GOB_Festivities_Trader` treasure table or Roah Moonglow which i think is under `GOB_Quartermaster` treasure table.
